// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dttecdbdhwygopudcgby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0dGVjZGJkaHd5Z29wdWRjZ2J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MzE5MDEsImV4cCI6MjA2OTQwNzkwMX0.1PzLQ3iVrHkqZBx1TqcFQ89UQKF2ebAtymxZO7fNFxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});